project:
  type: website
  output-dir: docs

website:
  title: "Luciano Lu - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes
        menu:
          - href: weekly-notes/week-01-notes.qmd
            text: Week 1
          - href: weekly-notes/week-02-notes.qmd
            text: Week 2
      - text: Labs
        menu:
          - href: Labs/lab_0/lab0_template.qmd
            text: Lab 0
      - text: Assignments
        menu:
          - href: assignments/assignment_1/assignment1_template.qmd
            text: "Assignment 1: Census Data Exploration"
          - href: assignments/assignment_2/Luciano_Lu_assignment2.qmd
            text: "Assignment 2: Data Visualization with ggplots"
          - href: assignments/midterm/appendix_nolog.qmd
            text: "Midterm Project"
          - href: assignments/midterm/Presentation_slides.qmd
            text: "Midterm PPT"
          - href: assignments/assignment_2/Luciano_Lu_assignment4.qmd
            text: "Assignment4"
format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto

